### ISSUE TITLE
你好，请问对应的客户端的配置文件该怎写呀？

### ISSUE THREAD

**Issue by daoxunchen** [HappyLife-page/v2ray#2]

**Comment by HappyLife-page** [comment]
手機端不方便演示，請自行搜索v2ray客戶端配置

**Comment by BrandonMoo** [comment]
请问
```
"outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "[1]",
            "port": [2],
            "users": [
              {
                "id": "[3]",
                "alterId": [4]
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "[5]"
        }
      }
    }
  ]
```
上面5处都配置了，还是连接不上。

**Comment by HappyLife-page** [comment]
客户端下载：
https://github.com/2dust/v2rayN/releases/download/4.20/v2rayN-Core.zip

![image](https://user-images.githubusercontent.com/84018863/139515615-14429509-8272-4c38-96bf-a3f71e33d97b.png)
![image](https://user-images.githubusercontent.com/84018863/139515800-5891ae93-d04e-4db5-bed4-7a4b6f1671ac.png)
![image](https://user-images.githubusercontent.com/84018863/139515843-ddebb7d3-c3ef-4409-ad73-1f4ec47ad804.png)

**Comment by HappyLife-page** [comment]
> 请问
> 
> ```
> "outbounds": [
>     {
>       "protocol": "vmess",
>       "settings": {
>         "vnext": [
>           {
>             "address": "[1]",
>             "port": [2],
>             "users": [
>               {
>                 "id": "[3]",
>                 "alterId": [4]
>               }
>             ]
>           }
>         ]
>       },
>       "streamSettings": {
>         "network": "ws",
>         "security": "tls",
>         "wsSettings": {
>           "path": "[5]"
>         }
>       }
>     }
>   ]
> ```
> 
> 上面5处都配置了，还是连接不上。

https://github.com/HappyLife-page/v2ray/issues/2#issuecomment-955123386

**Comment by HappyLife-page** [comment]
新版v2rayN客户端配置：
![image](https://user-images.githubusercontent.com/84018863/196377785-9e6dec17-3971-4b4f-8e09-364159fc9583.png)
