### ISSUE TITLE
ubuntu 20.04 安装 v2ray 5.1.0时，v2ray服务无法启动

### ISSUE THREAD

**Issue by SalvadorLyons** [HappyLife-page/v2ray#4]
脚本正常输出了配置信息，但是使用systmctl status v2ray 发现无法服务无法启动，大佬能不能补充一下，你测试脚本的时候安装的v2ray版本。我想指定版本再试一次。

输出信息为：
Process: 5445 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=2)
Main PID: 5445 (code=exited, status=2)
CPU: 29ms
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: Stopped V2Ray Service.
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: Failed to start V2Ray Service.

Started V2Ray Service.
 flag provided but not defined: -config
 Usage of /usr/local/bin/v2ray:
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 5.
Stopped V2Ray Service.
v2ray.service: Start request repeated too quickly.
v2ray.service: Failed with result 'exit-code'.
Failed to start V2Ray Service.

**Comment by HappyLife-page** [comment]
使用v2ray 4版本
最新5版不应该有那么多变化，我空闲再测试修正

**Comment by SalvadorLyons** [comment]
> 使用v2ray 4版本
> 最新5版不应该有那么多变化，我空闲再测试修正

好的，谢谢大佬

**Comment by SalvadorLyons** [comment]
补充手动将脚本安装的v2ray指定为"v4.45.2"，此问题不再出现，这个问题也许是5.0导致。有相同的问题的小伙伴可以采用这种临时方案过渡一下。
