### ISSUE TITLE
服务启动出错

### ISSUE THREAD

**Issue by wanyx2015** [HappyLife-page/v2ray#5]
脚本：v2ray_installation_centos7

目前安装好后的v2ray 版本为 5.1.0

其服务运行命令为：

/usr/local/bin/v2ray run -c /usr/local/etc/v2ray/config.json

原命令运行会出错。

另外，麻烦推荐手机端 支持 vless 协议的 v2ray 客户端，谢谢！

**Comment by HappyLife-page** [comment]
新版v5官方安装脚本启动命令未及时跟随5版本更新!已添加修正
手机客户端苹果shadowrocket，安卓v2rayNG
